config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :employees 
  resources :users do
    member do
      get :personal_page
    end
  end
  resources :problems do 
    member do
      get :accept
    end
  end
  ## Accept issue
  post "/acce_matt", to: "problems#accept_mat"
  post "/accept", to: "problems#accept_issue"
  get "/accept", to: "problems#accept"
  
  get "/submit", to: "problems#new"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get "/", to: "homepage#home_page"
  #home page
  get "/", to: 'homepage#home_page'

  get "/new", to: "sessions#new"
  post "/user", to: "sessions#create"
  post "/login", to: "sessions#login"
  get "/index", to: "users#index"
  get "/log_out", to: "users#log_out"
  get "/login", to: "sessions#log_in"
  get "/new_issue", to: "issues#new"
  # post "/issue", to: "issues#create"
  get "/show", to: "issues#show"
  # get "/pass", to: "employees#pass"
  post "/problem", to: "employees#update"
  get "/issue", to: "employees#issue"
  get "/new_user", to: "sessions#new_user"
  # post "/employee", to: "sessions#create_user"
  get "/user", to: "employees#user"
  get "/profile", to: "users#profile"
  post "/upprofile", to: "users#update_profile"
  post "/edit_user", to: "users#update"
  post "/pass", to: "employees#pass"
  post "/block", to: "employees#block"
  post "/active", to: "employees#active"
  get "/submit_issue", to: "problems#new"
  post "/submit_issue", to: "problems#create"
  # post "/issue_accept", to: "users#accept_issue"
  post "/feed", to: "sessions#comment"
  post "/confirm", to: "problems#confirm"
  # post "/bill_of_material", to: "users#accept_issue"
  post "/confirm_issue", to: "employees#confirm"
  get "/report", to: "employees#report"
  get "/about", to: "employees#about"
  post "/select", to: "employees#about"
  get "/confirmed_issue", to: "users#confirmed_issue"
  get "/help", to: "additions#help"
  get "/addition", to: "additions#addition"
  post "/gover", to: "additions#new_gover"
  post "/city", to: "additions#new_city"
  post "/cat", to: "additions#new_cat"
  post "/mat", to: "additions#new_mat"
  get "/accept_status", to: "users#accept_status"
  # post "/accept", to: "users#accept_problem"
  post "/join_issue", to: "users#join"
  #meassages
  get "/meassage", to: "users#meassage"
  #image
  post "/image", to: "users#upimage"
  ##personal_page
  get "/personal_page", to: "users#personal_page"
  get "/log", to: "users#log"

  ##Add Bio
  post "/bio", to: "users#add_bio"
  ## supporte money
  post "/money", to: "users#support_money"
  ## support matterails
  post '/supmat', to: "users#support_mat"

  ##spervisor
  get "/supervisor", to: "users#supervisor"
  resources :users do
    member do
      patch :accept
    end
  end
  resources :issues
  resources :employees do
    member do
      patch :block
      post :pass
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  layout 'application'
  before_action :check_login
  before_action :set_bass ,only: [:bass]
  before_action :check_type
  before_action :check_status
  # before_action :set_user ,only: [:edit]
  # before_action :confirm_employee_type, except: [:new, :create]

  def user
    @user = User.where(:id=>session[:user_id]) 
    @users=User.volunteer.where(["first_name LIKE ?","%#{params[:first_name]}%"])

  end
  def block 
    respond_to do |format|
    
      if User.where(:id=>update_params[:id]).update_all(:accountstatu=>false)
          format.html { redirect_to '/user', notice: "this user are blocked." }
      else
        flash[:error_blook]="something went wrong"
        format.html { redirect_to '/user', notice: "something went wrong." }
      end
    end
  end
  def active
    # @user=User.find_by(id: active_params[:id])
    # @user.accountstatu=true
    respond_to do |format|
      if User.where(:id=>active_params[:id]).update_all(:accountstatu=>true)
        format.html { redirect_to '/user', notice: "this user are active." }
      else
        flash[:error_active]="something went wrong"
        format.html { redirect_to '/user', notice: "something went wrong." }
      end
    end
  end
  def pass
    # @problem = Problem.where(params[:id])
    # @problem = Problem.find_by(id: pass_params[:id])
    # @problem.status="Passed"
    if Problem.where(id:pass_params[:id]).update_all(:status=>"Passed")
      redirect_to '/issue'
    else
      redirect_to "/issue"
    end

  end
  def issue
    @user = User.where(:id=>session[:user_id]) 
    @problems = Problem.order("id DESC").issue_submitted.with_attached_image
  end
  def confirm
    # problem=Problem.find_by(id: confirm_params[:id])
    Problem.where(id:confirm_params[:id]).update_all(:status=>"Confirmed")
    respond_to do |format|
      format.html { redirect_to '/index', notice: "Photo was successfully created." }
    end
    # problem.status="Confirmed"
    # problem.update(confirm_params)
  end
  def report
    # @problems = Problem.with_attached_image.where(:status=>params[:status])
    # render 'reports'
  end
  def about

  end
  private

    def set_pass
     @problem = Problem.find(params[:id])
    end
    def set_user
     @user = User.find(params[:id])
    end
    def problem_params
     params.require(:problem).permit(:image, :cordinates,  :status, :desciption, :governorate_id, :category_id,:city_id,:user_id)  
    end
    def update_params
      params.require(:block).permit(:accountstatu,:id)  

    end
    def active_params
      params.require(:active).permit(:accountstatu,:id)  

    end
    def pass_params
      params.require(:pass).permit(:status,:id)  
    end
    def confirm_params
      params.require(:confirm_issue).permit(:status,:id)  
    end
    #  def select_params
    #   params.require(:select).permit(:status)  
    #  end
     
  
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Table - Brand</title>
    <meta name="theme-color" content="#2eb8e6">
    <link rel="icon" type="image/jpeg" sizes="736x552" href="assets/img/fixit.jpg">
    <link rel="icon" type="image/jpeg" sizes="736x552" href="assets/img/fixit.jpg">
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="manifest" href="manifest.json">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i900900i">
    <link rel="stylesheet" href="assets/fonts/fontawesome-all.min.css">
    <link rel="stylesheet" href="assets/fonts/font-awesome.mincss">
    <link rel="stylesheet" href="assets/fonts/fontawesome5-overrides.min.css">
    <link rel="stylesheet" href="assets/css/styles.min.css">
</head>

<body id="page-top" class=body>
    <div id="wrapper">
      
      
                
                <div class="container-fluid">
                    <h3 class="text-dark mb-4">Users</h3>
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 text-nowrap">
                                    <div id="dataTable_length" class="dataTables_length" aria-controls="dataTable">
                                        <label class="form-label">Show&nbsp;<select
                                                class="d-inline-block form-select form-select-sm">
                                                <option value="10" selected="">10</option>
                                                <option value="25">25</option>
                                                <option value="50">50</option>
                                                <option value="100">100</option>
                                            </select>&nbsp;</label></div>
                                </div>
                                <div class="col-md-6">
                                    <div class="text-md-end dataTables_filter " id="dataTable_filter"><label
                                            class="form-label">
                                                <%= form_tag(users_path, :method =>'get') do%>
                                                    <%=text_field_tag :first_name, params[:first_name], class:" form-control-sm", placeholder:"Search"%>
                                                   <button class="btn btn-primary py-0"><i class="fas fa-search"></i></button>
                                                <%end%>
                                            </label>
                                    </div>
                                </div>
                                <div>
                                </div>
                            </div>
                            <div class="table-responsive table mt-2" id="dataTable" role="grid"aria-describedby="dataTable_info">
                                <table class="table my-0" id="dataTable">
                                    <thead>
                                        <tr>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>Phone Number</th>
                                            <th>State</th>
                                            <th>City</th>
                                            <th>Account Status</th>
                                            <th>Action</th>
                                            <th>Submitted Issues</th>
                                        </tr>
                                    </thead>
                                        <tbody>

                                            <% @users.each do |user| %>
                                                 <tr>
                                                     <td ><%=user.first_name%></td>
                                                     <td ><%=user.last_name%></td>
                                                     <td ><%=user.phone%></td>
                                                     <%@city=City.where(:id=>1)%>
                                                        
                                                        <% @city.each do |city| %>
                                                            <%@gove=Governorate.where(:id=>city.governorate_id)%>
                                                        <% end %>
                                                        
                                                        <% @gove.each do |gove| %>
                                                        
                                                        <td> <%=gove.name%></td>
                                                     <% end %>
                                                     <% @city.each do |city| %>
                                                        <td><%=city.name%></td>
                                                     <% end %>
                                                     
                                                     <td><%=user.accountstatu%></td>
                                                     <td class=td>
                                                        <form action='/block' method='POST'>
                                                            <input type='hidden' name='authenticity_token' value="<%= form_authenticity_token%>">
                                                            <input type='hidden' name='block[accountstatu]' value=false>
                                                            <input type='hidden' name='block[id]' value=<%=user.id%>>
                                                            <input type=submit value=Block class="btn btn-primary d-block btn-user">
                                                        </form>
                                                        <form action='/active' method='POST'>
                                                            <input type='hidden' name='authenticity_token' value="<%= form_authenticity_token%>">
                                                            <input type='hidden' name='active[accountstatu]' value=true>
                                                            <input type='hidden' name='active[id]' value=<%=user.id%>>
                                                            <input type=submit value=Active class="btn btn-primary d-block btn-user">
                                                        </form>
                                                     </td>
                                                     <td>
                                                        <%=Problem.where(:user_id=>user.id).count%>
                                                     </td>
                                                 </tr>
                                            <% end %>

                                        </tbody>

                                </table>
                            </div>
                            <div class="row">
                                <div class="col-md-6 align-self-center">
                                    <p id="dataTable_info" class="dataTables_info" role="status" aria-live="polite">Showing 1 to 10 of 27</p>
                                </div>
                                <div class="col-md-6">
                                    <nav
                                        class="d-lg-flex justify-content-lg-end dataTables_paginate paging_simple_numbers">
                                        <ul class="pagination">
                                            <li class="page-item disabled"><a class="page-link" href="#"aria-label="Previous"><span aria-hidden="true">«</span></a></li>
                                            <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                            <li class="page-item"><a class="page-link" href="">2</a></li>
                                            <li class="page-item"><a class="page-link" href="">3</a></li>
                                            <li class="page-item"><a class="page-link" href="" aria-label="Next"><span aria-hidden="true">»</span></a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div><a class="border rounded d-inline scroll-to-top" href=""><i class="fas fa-angle-up"></i></a>
    </div>
    <script ></script>
    <script ></script>
</body>

</html>

app/views/employees/issue.html.erb
<!DOCTYPE html>
<html>
<body id="page-top"class=body>
    <div id="wrapper">
       
        <div class="d-flex flex-column" id="content-wrapper">
            <%# <div id="content"> %>
                    <div class="container-fluid">
                
                <div class="container-fluid">
                    <div class="d-sm-flex justify-content-between align-items-center mb-4">
                        <h3 class="text-dark mb-0">Submitted Issues</h3>
                    </div>
                    <div class="row">
                        <div class="col">
                            
                            <div class="container">

                                <div class="row">
                            
                                        
                                <% @problems.each do |problem| %>


                                    <form action=/pass method=post class="col-md-4" >

                                        <input type='hidden' name='authenticity_token' value="<%= form_authenticity_token%>">
                                        <div class="blog-card blog-card-blog">
                                            <div class="blog-card-image">
                                                <a href="#">  
                                                    <% if (problem.image.attached?) %>
                                                       <%=image_tag(url_for(problem.image))%>
                                                       <% else %>
                                                         <p>no image</p>
                                                    <% end %> </a>
                                                <div class="ripple-cont"></div>
                                            </div>
                                            <div class="blog-table">
                                                <h6 class="blog-category blog-text-success">
                                                    <%@cat=Category.where(:id=>problem.category_id)%>

                                                        <% @cat.each do |cat| %> 
                                                            <i class="far fa-newspaper"></i> <%=cat.name%>
                                                        <% end %>   
                                                </h6>
                                                <div>
                                                    <h4 class="blog-card-caption">Location:</h4>
                                                    <div>
                                                        <span>Governorate:</span>
                                                        <%@city=City.where(:id=>problem.city_id)%>
                                                        <% @city.each do |city| %>
                                                             <%@gover=Governorate.where(:id=>city.governorate_id)%>
                                                             <% @gover.each do |gover| %>
                                                             <span><%=gover.name%></span>
                                                             <%end%>
                                                        <% end %>
                                                    </div>
                                                    <div>
                                                        <span>City:</span>
                                                        <% @city.each do |city| %>
                                                            <span><%=city.name%></span>
                                                        <%end%>
                                                    </div>
                                                </div>
                                                <div>
                                                    <h4 class="blog-card-caption">Description</h4>
                                                    <p class="blog-card-description">
                                                        <%=problem.desciption %>
                                                    </p>
                                                </div>
                                                <div>
                                                    <h4 class="blog-card-caption">Submitted by:</h4>
                                                    <div>
                                                        <span>user:</span>
                                                        <%@user=User.where(:id=>problem.user_id)%>
                                                        
                                                        <% @user.each do |user| %>
                                                            <%x=user.first_name%>
                                                            <%y=user.last_name%>
                                                            <span > <%= link_to "#{x} #{y}",personal_page_user_path(user),:class=>"link-dark" %></span>
                                                        <% end %>
                                                        
                                                    </div>
                                                </div>
                                                <input type='hidden' name='pass[id]'value="<%=problem.id%>">
                                                <input type='hidden' name='pass[status]'value="pass">
                                                <input type=submit value=Pass class="btn btn-primary d-block btn-user w-100">
                                                <br>
                                                <%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger d-block btn-user w-100" %>
                                            </div>

                                        </div>
                                    </form>

                                <%end%>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
          
        </div>
        <a class="border rounded d-inline scroll-to-top" href="" style="margin-right: 60px;">
            <i class="fas fa-angle-up"></i>
        </a>
        <a  class="border rounded d-inline scroll-to-top"href="/submit_issue">
        <button class="btn btn-primary add-issue fa fa-plus" type="button" data-toggle="modal" data-target="#submit_issue" ></button>
        </a>
    </div>
    
    <div id="submit_issue" class="modal fade" role="dialog">
        <div class="modal-dialog">
      
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body">
              <p>Some text in the modal.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
      
        </div>
    </div>
   
</body>

</html>

app/views/employees/user.html.erb
<!DOCTYPE html>
<html>
<style>
    .action {
        width: 100%;
        display: flex;
        flex-flow: column nowrap;
        justify-items: center;
    }

    .action .btn {
        width: 80%;
        margin: 3px;
        height: 35px;
        padding: 5px;
    }

    .action form {
        width: 100%;
    }
    .users-row td{
        text-align: center;
        vertical-align: middle;
    }
</style>

<body id="page-top" class=body>
    <div id="wrapper">



        <div class="container-fluid">
            <h3 class="text-dark mb-4">Users</h3>
            <div class="card shadow">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 text-nowrap">
                            <div id="dataTable_length" class="dataTables_length" aria-controls="dataTable">
                                <label class="form-label">Show&nbsp;
                                    <select class="d-inline-block form-select form-select-sm">
                                        <option value="10" selected="">10</option>
                                        <option value="25">25</option>
                                        <option value="50">50</option>
                                        <option value="100">100</option>
                                    </select>&nbsp;
                                </label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="text-md-end dataTables_filter " id="dataTable_filter"><label class="form-label">
                                    <%= form_tag('/user', :method=>'get') do%>
                                        <%=text_field_tag :first_name, params[:first_name], class:" form-control-sm",placeholder:"Search"%>
                                        <button class="btn btn-primary py-0"><i class="fas fa-search"></i></button>
                                    <%end%>
                                </label>
                            </div>
                        </div>
                        <div>
                        </div>
                    </div>
                    <div class="table-responsive table mt-2" id="dataTable" role="grid"
                        aria-describedby="dataTable_info">
                        <table class="table my-0 text-center" id="dataTable">
                            <thead>
                                <tr>
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th>Phone Number</th>
                                    <th>State</th>
                                    <th>City</th>
                                    <th>Account Status</th>
                                    <th>Action</th>
                                    <th>Submitted Issues</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @users.each do |user| %>
                                    <tr class="users-row">
                                        <td>
                                            <%= link_to "#{user.first_name} " ,personal_page_user_path(user),:class=>
                                                "link-dark" %>
                                        </td>
                                        <td>
                                            <%= link_to "#{user.last_name} " ,personal_page_user_path(user),:class=>
                                                "link-dark" %>
                                        </td>
                                        <td>
                                            <%=user.phone%>
                                        </td>
                                        <%@city=City.where(:id=>1)%>
                                            <% @city.each do |city| %>
                                                <%@gove=Governorate.where(:id=>city.governorate_id)%>
                                        <% end %>
                                            <% @gove.each do |gove| %>
                                            <td>
                                                <%=gove.name%>
                                            </td>
                                        <% end %>
                                        <% @city.each do |city| %>
                                            <td>
                                                <%=city.name%>
                                            </td>
                                        <% end %>
                                        <%if user.accountstatu==true%>
                                            <td>Active</td>
                                        <%else%>
                                            <td>Blocked</td>
                                        <%end%>
                                        <td class=action>
                                            <%# <form action='/block'method='POST'> %>
                                            <%= form_tag({:controller=>'employees',:action=>'block'},:remote=> true, method: :post) do%>
                                                <%# <input type='hidden'name='authenticity_token'value="<%= form_authenticity_token%>
                                                <input type='hidden'name='block[accountstatu]'value=false>
                                                <input type='hidden'name='block[id]'value=<%=user.id%>>
                                                <input type=submit value=Block class="btn btn-warning d-block">
                                            <% end %>
                                            <%= form_tag({:controller=>'employees',:action=>'active'},:remote=> true, method: :post) do%>
                                                <%# <input type='hidden'name='authenticity_token'value="<%= form_authenticity_token%>
                                                <input type='hidden'name='active[accountstatu]'value=true>
                                                <input type='hidden'name='active[id]'value=<%=user.id%>>
                                                <input type=submit value=Activate class="btn btn-primary d-block">
                                            <% end %>
                                            <%= link_to 'Destroy' , user, method: :delete, data: {confirm: 'Are you sure?'}, class:"btn btn-danger"%>

                                        </td>
                                        <td>
                                            <%=Problem.where(:user_id=>
                                                user.id).count%>
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-md-6 align-self-center">
                            <p id="dataTable_info" class="dataTables_info" role="status" aria-live="polite">Showing 1 to
                                10 of 27</p>
                        </div>
                        <div class="col-md-6">
                            <nav class="d-lg-flex justify-content-lg-end dataTables_paginate paging_simple_numbers">
                                <ul class="pagination">
                                    <li class="page-item disabled"><a class="page-link" href="#"
                                            aria-label="Previous"><span aria-hidden="true">«</span></a></li>
                                    <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                    <li class="page-item"><a class="page-link" href="">2</a></li>
                                    <li class="page-item"><a class="page-link" href="">3</a></li>
                                    <li class="page-item"><a class="page-link" href="" aria-label="Next"><span
                                                aria-hidden="true">»</span></a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div><a class="border rounded d-inline scroll-to-top" href=""><i class="fas fa-angle-up"></i></a>
    </div>
    <script></script>
    <script></script>
</body>

</html>