config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :employees 
  resources :users do
    member do
      get :personal_page
    end
  end
  resources :problems do 
    member do
      get :accept
    end
  end
  ## Accept issue
  post "/acce_matt", to: "problems#accept_mat"
  post "/accept", to: "problems#accept_issue"
  get "/accept", to: "problems#accept"
  
  get "/submit", to: "problems#new"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get "/", to: "homepage#home_page"
  #home page
  get "/", to: 'homepage#home_page'

  get "/new", to: "sessions#new"
  post "/user", to: "sessions#create"
  post "/login", to: "sessions#login"
  get "/index", to: "users#index"
  get "/log_out", to: "users#log_out"
  get "/login", to: "sessions#log_in"
  get "/new_issue", to: "issues#new"
  # post "/issue", to: "issues#create"
  get "/show", to: "issues#show"
  # get "/pass", to: "employees#pass"
  post "/problem", to: "employees#update"
  get "/issue", to: "employees#issue"
  get "/new_user", to: "sessions#new_user"
  # post "/employee", to: "sessions#create_user"
  get "/user", to: "employees#user"
  get "/profile", to: "users#profile"
  post "/upprofile", to: "users#update_profile"
  post "/edit_user", to: "users#update"
  post "/pass", to: "employees#pass"
  post "/block", to: "employees#block"
  post "/active", to: "employees#active"
  get "/submit_issue", to: "problems#new"
  post "/submit_issue", to: "problems#create"
  # post "/issue_accept", to: "users#accept_issue"
  post "/feed", to: "sessions#comment"
  post "/confirm", to: "problems#confirm"
  # post "/bill_of_material", to: "users#accept_issue"
  post "/confirm_issue", to: "employees#confirm"
  get "/report", to: "employees#report"
  get "/about", to: "employees#about"
  post "/select", to: "employees#about"
  get "/confirmed_issue", to: "users#confirmed_issue"
  get "/help", to: "additions#help"
  get "/addition", to: "additions#addition"
  post "/gover", to: "additions#new_gover"
  post "/city", to: "additions#new_city"
  post "/cat", to: "additions#new_cat"
  post "/mat", to: "additions#new_mat"
  get "/accept_status", to: "users#accept_status"
  # post "/accept", to: "users#accept_problem"
  post "/join_issue", to: "users#join"
  #meassages
  get "/meassage", to: "users#meassage"
  #image
  post "/image", to: "users#upimage"
  ##personal_page
  get "/personal_page", to: "users#personal_page"
  get "/log", to: "users#log"

  ##Add Bio
  post "/bio", to: "users#add_bio"
  ## supporte money
  post "/money", to: "users#support_money"
  ## support matterails
  post '/supmat', to: "users#support_mat"

  ##spervisor
  get "/supervisor", to: "users#supervisor"
  resources :users do
    member do
      patch :accept
    end
  end
  resources :issues
  resources :employees do
    member do
      patch :block
      post :pass
    end
  end
end

app/models/problem.rb
class Problem < ApplicationRecord
    has_one_attached :image

    scope :issue_submitted, -> { where(:status => "Submitted")}
    scope :issue_passed, -> { where(:status => "Passed")}
    scope :issue_confirmed, -> { where(:status => "confirmed")}
    scope :accept_issue, -> { where(:status => "Accepted")}
    # Ex:- scope :active, -> {where(:active => true)}
    # scope :desc,  order("problems.id DESC")
    # Ex:- scope :active, -> {where(:active => true)}
    validates :image, presence: true
    
    def self.search(search)
        if search
            # where([["status LIKE ?","%#{search}%"]])
            where(["status LIKE ?","%#{search}%"])
        else
            issue_passed
        end
    end

    # Ex:- scope :active, -> {where(:active => true)}
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  layout 'application'
  before_action :set_problem, only: %i[ show edit update destroy ]
  before_action :blok_or_active,except: [:show, :edit, :update, :confirm] 
  before_action :check_login
  before_action :check_status
  # GET /problems or /problems.json
  def index
    @problems = Problem.where(["status LIKE ?","%#{params[:search]}%"]).with_attached_image
    @x=params[:id]
    @city=City.where(:governorate_id=> params[:id])
    # @accept=Accept.where("problem_id: Problem.where(id:81)")
    # if @accept.required_volunteer >5
    #   @x="nlkhvj;d"
    # end

  end

  # GET /problems/1 or /problems/1.json
  def show
    @problems = Problem.issue_submitted.with_attached_image
    @user=User.where(:id=>session[:user_id])
  end

  # GET /problems/new
  def new
    
    @problem = Problem.new
    @x=params[:id]
    @city=City.all
  end

  # GET /problems/1/edit
  def edit
    if user = Problem.where(:id=>params[:id]).present?
      @problem = Problem.find(params[:id])
      @city=City.all
    else
      redirect_to '/index'
    end
  end

  # POST /problems or /problems.json
  def create
    user=User.find_by(:id=>session[:user_id]) 
    if user.accountstatu==false
      redirect_to new_problem_path
    else
      @problem = Problem.new(problem_params)
      @problem.user_id=session[:user_id]
      respond_to do |format|
        if @problem.save
          if user.user_type=="Volunteer"
          format.html { redirect_to '/index', notice: "Problem was successfully created." }
          format.json { render :show, status: :created, location: @problem }
        elsif user.user_type=="Employee"
          format.html { redirect_to '/issue', notice: "Problem was successfully created." }
          format.json { render :show, status: :created, location: @problem }
          end
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @problem.errors, status: :unprocessable_entity }
        end
      end
    end
   
  end

  # PATCH/PUT /problems/1 or /problems/1.json
  def update
    user=User.find_by(:id=>session[:user_id]) 
    respond_to do |format|
      if @problem.update(problem_params)
        if user.user_type=="Employee"
        format.html { redirect_to '/issue', notice: "Problem was successfully updated." }
        format.json { render :show, status: :ok, location: @problem }
        elsif user.user_type=="Volunteer"
          format.html { redirect_to '/index', notice: "Problem was successfully updated." }
          format.json { render :show, status: :ok, location: @problem }
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1 or /problems/1.json
  def destroy
    user=User.find_by(:id=>session[:user_id]) 
    @problem.destroy
    if user.user_type=="Employee"
    respond_to do |format|
      format.html { redirect_to '/issue', notice: "Problem was successfully destroyed." }
      format.json { head :no_content }
    end
      elsif user.user_type=="Volunteer"
        respond_to do |format|
          format.html { redirect_to '/index', notice: "Problem was successfully destroyed." }
          format.json { head :no_content }
        end
    end
  end
  def confirm 
      user=User.where(:id=>session[:user_id])
      respond_to do |format|
      confirm=Confirm.new(confirm_prams)
        if user=Confirm.find_by(:problem_id=>confirm_prams[:problem_id],:user_id=>session[:user_id])
         Confirm.where(:problem_id=>confirm_prams[:problem_id],:user_id=>session[:user_id]).update(:confirmed=>confirm_prams[:confirmed])
           format.html { redirect_to '/index', notice: "Confirmed." }
        else
           confirm.user_id=session[:user_id]
           if confirm.save 
              format.html { redirect_to '/index', notice: "Confirmed." }
           end
        end
      end
  end
  def accept
    @problem = Problem.find_by(:id=>params[:id])
    @accept = Accept.find_by(:user_id=> session[:user_id])
  end
  def accept_issue
    accept=Accept.new(accept_params)
    accept.user_id=session[:user_id]
    accept.problem_id=params[:problem_id]
    accept.totale_cost = 0
    respond_to do |format|
      if accept.save 
        Problem.where(id:params[:problem_id]).update_all(:status=>"Accepted")
        User.where(:id=>session[:user_id]).update_all(:supervisor=>true)
        format.html { redirect_to '/accept', notice: "accepted." }
      else
          flash[:error_accept]="something went wrong"
          format.html { redirect_to '/accept', notice: "something went wrong." }
      end
    end
  end
  def accept_mat 
    bill = BillOfMaterial.new(matt_params)
    bill.accept_id= accept.id
    bill.material_id= params[:material_id]
    accept = Accept.find_by(:problem_id=>params[:problem_id])
    total = accept.totale_cost
    respond_to do |format|
      if bill.save
        total_cost = total+(bill.cost * bill.quantity)
        Accept.where(:id=>accept.id).update_all(:totale_cost=>total_cost)
        format.html { redirect_to '/accept', notice: "accepted." }
      else
        # flash[:error_accept]="something went wrong"
        format.html { redirect_to '/accept', notice: "something went wrong." }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def problem_params
      
     params.require(:problem).permit(:image, :cordinates,  :status, :desciption, :governorate_id, :category_id,:city_id,:user_id)  

    end
    def confirm_prams
      params.require(:confirm).permit(:problem_id ,:user_id ,:confirmed)
   end
   def accept_params
    params.require(:accept).permit(:user_id,:required_volunteer, :problem_id, :total_cost)
   end
   def matt_params
    params.require(:acce_matt).permit(:material_id, :cost, :quantity,:accept_id)
   end

end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_form.html.erb
<%= stylesheet_link_tag 'submit_issue'%>

<%= form_with(model: problem ,class:"container-form") do |form| %>
  <% if problem.errors.any? %>
    <div id="error_explanation">
      <h2 class=h2><%= pluralize(problem.errors.count, "error") %> pleases enter the image</h2>
      <ul>
        <% problem.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="choose-photo-form">
    <div class="select-photo custom-file">
      <div class="mb-5">
        <div class="form-label custom-file-input" id="formFile" onchange="preview()"><%= form.file_field :image %></div>
        <label class="custom-file-label">Choose Image</label>
      </div>
    </div>
    <img id="frame" class="img-preview" width="250px" height="300px" name="image" <%=image_tag('image-preview2.png')%>
  </div>
    <div class="issueInfo">
      <div class="issueInfoParts">
        <label>State</label>
        <select  class="form-select" for="floatinginput" placeholder="HGsOFT" >
          <option ></option>
          <%@gover=Governorate.all%>
          <% @gover.each do |go| %>
            <option value="<%= go.id%>">
                <%=go.name%>
            </option>
          <% end %>
        </select>
      </div>
        
      <div class="issueInfoParts">
          <label>City</label>
          <select class="form-select form-select"name="problem[city_id]"  for="floatinginput" placeholder="city"  >
              <option ></option>
                <% @city.each do |ct| %>
                  <option value="<%=ct.id%>">
                        <%=ct.name%>
                  </option>
              <% end %>
          </select>
      </div>
      <div class="issueInfoParts">
          <label > Category </label>
          <%@cat=Category.all%>
          <select class="form-select form-select" name="problem[category_id]" for="floatinginput" placeholder="category"  >
              <option ></option>
              <% @cat.each do |ct| %>
                  <option value="<%=ct.id%>">
                        <%=ct.name%>
                  </option>
              <% end %>
          </select>
      </div>
      <div class="issueInfoParts">
        <label>Description</label>
        <%= form.text_area :desciption, label: "desciption",class:"form-control" ,placeholder:"Add description..." ,rows:"5" ,cols:"22" %>
      </div>
      <button class="btn btn-primary submit-issue" type="submit">Submit Issue</button>
    </div>
<% end %>

app/views/problems/accept.html.erb
 <style>
  
 
 </style>
<%= stylesheet_link_tag 'accept' %>

<body>
 <div id="accept-form" class="accept-modal">
   <div class="modal-content-accept">
     <div class="modal-body-accept">
      <div> 
      <% if @accept.present?%>
      <% accept = Accept.find_by(:user_id=> session[:user_id])%>
      <%  @problem = Problem.find_by(:id=>accept.problem_id) %>
        number of volunteers: <%= accept.required_volunteer%>       
      </div>
      <% else %>
      <% end %>
       
            <div>
            <div>Materials:</div>
            <div class="table-responsive">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <td class="text-center">Name</td>
                    <td class="text-center">Cost</td>
                    <td class="text-center">Quantity</td>
                    <td class="text-center">Total</td>
                    <%# <td class="text-center"></td> %>
                    <%# <td><button class="btn btn-md btn-primary" id="addBtn" type="button">+</button></td> %>
                  </tr>
                </thead>
                <tbody >
                  <% if @accept.present?%>
                      <% billofmat = BillOfMaterial.where(:accept_id=>accept.id) %>
                      <% billofmat.each do |bill|%>
                        <tr>
                          <% mat = Material.find_by(:id=> bill.material_id)%>
                          <td class="row-index text-center">
                            <%= mat.name%>
                          </td>
                          <td class="row-index text-center">
                           <%= bill.cost%>
                          </td>
                          <td class="row-index text-center">
                            <%= bill.quantity%>
                          </td>
                        </tr>
                      <% end %>
                  <% end %>

                  </tbody>
              </table>
               <% if @accept.present?%>
                <div class="row-index text-center">
                   total cost: <%= accept.totale_cost%>
                </div>
              <% end %>
            </div>
          </div>
      </div>
    </div>
  </div>
    <% if @accept%>
    <div>Number of needed volunteers:<i class="fa fa-check" aria-hidden="true"></i>
    </div>
    <% else%>
    <div>Number of needed volunteers:</i>
    </div>
      <div class=num-volu>
        <%= form_tag({:controller=>'problems',:action=>'accept_issue'},:remote=> true, :local=> true, html: {:id => "post-com" },method: :post) do %>
          <%# <input type='hidden' name='authenticity_token' value="<%= form_authenticity_token%>
          <input type=number name=accept[required_volunteer]>
          <%= hidden_field_tag(:problem_id, params[:problem_id],value:@problem.id) %>
          <input type=submit class='btn btn-outline-info' id='num-volu' value=Reuest>
        <% end %>
      </div>
    <% end %>

  <% @cat = Category.find_by(:id=>@problem.id)%>
  <%= form_tag({:controller=>'problems',:action=>'accept_mat'},:remote=> true, :local=> true, html: {:id => "post-com" },method: :post) do %>
    <%# <input type='hidden' name='authenticity_token' value="<%= form_authenticity_token%>
    <%= select_tag :material_id,options_from_collection_for_select(Material.where(:category_id=>@problem.category_id).order(:name), :id, :name,params[:material_id]), class:"selectt-mat", include_blank: "Choose the material?" %>
    <%# <%= number_field_tag(:cost, params[:cost]) %> 
    <label>cost:</label>
    <input type=number name=acce_matt[cost]>
    <%= hidden_field_tag(:problem_id, params[:problem_id],value:@problem.id) %>
    <%# <%=number_field_tag(:quantity, params[:quantity])%> 
    <label>Quantity:</label>
    <input type=number name=acce_matt[quantity]>
    <br>
    <input type=submit class='btn btn-outline-info' value=Reuest>
  <% end %>
  <a href='/accept_status'>
    <button>Finished</button>
  </a>
  <script>
  $('#num-volu').click(function(){
    $('.num-volu').hide()
    $('.fa-check').show()
  });
  </script>
</body>

app/views/problems/edit.html.erb
 <%= render 'form', problem: @problem %> 

app/views/problems/fixed.html.erb
<%= stylesheet_link_tag 'submit_issue'%>

<%= form_with(model: problem ,class:"container-form") do |form| %>
  <% if problem.errors.any? %>
    <div id="error_explanation">
      <h2 class=h2><%= pluralize(problem.errors.count, "error") %> pleases try again</h2>
      <ul>
        <% problem.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="choose-photo-form">
    <div class="select-photo custom-file">
      <div class="mb-5">
        <div class="form-label custom-file-input" id="formFile" onchange="preview()"><%= form.file_field :image %></div>
        <label class="custom-file-label">Choose Image of fixed issue</label>
      </div>
    </div>
    <%=image_tag('image-preview2.png', id:"frame", class:"img-preview", style:"width: 250px; height: 300px;", name:"image")%>
    </div>
    <div class="issueInfo">
      <div class="issueInfoParts">
        <label>Report</label>
        <%= form.text_area :desciption, label: "desciption",class:"form-control" ,placeholder:"Add report about this issue after fixing it..." ,rows:"7" ,cols:"30" %>
      </div>
      <button class="btn btn-primary submit-issue" type="submit">Issue Fixed</button>
    </div>
<% end %>

app/views/problems/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to  "log out", "log_out" %>
<%= form_tag problems_path, :method =>'get' do%>
 <%@gover=Governorate.all%>
  <%# <%=text_field_tag :search, params[:search]%> %>
  
      
  
  
  <% @gover.each do |go| %>
    
    <% end %>
    
  
<%# <%= select_tag :search,   options_from_collection_for_select(Governorate.all.order(:name), :id, :name, params[:search]), id: "different_option_value_html", onchange: "this.form.submit();", include_blank: "Which status ?"%> %>


  <%= submit_tag "Search"%>
<%end%>

<h1><%=@x%></h1>

<%= form_tag problems_path, :method =>'get' do%>
    <%=text_field_tag :first_name, params[:search], class:" form-control-sm", placeholder:"Search"%>
    <%= select_tag :id,   options_from_collection_for_select(Governorate.all.order(:name), :id, :name, params[:id]), id: "different_option_value_html", onchange: "this.form.submit();", include_blank: "Which status ?"%>
    <%= submit_tag "city"%>
<%end%>
<select>

<% @city.each do |c| %>
<option>
  <%=c.name%>

</option>
<% end %>
</select>
<h1>Problems</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  
    <% @problems.each do |problem| %>
      <tr>
      <td>
          <%= problem.desciption%>
      </td>
      <td>
      <% if (problem.image.attached?) %>
        <%=image_tag(url_for(problem.image))%>
        <% else %>
          <p>no image</p>
      <% end %>
     
      </td>
      
        <td><%= link_to 'Show', problem %></td>
        <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
        <td><%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Problem', new_problem_path %>

app/views/problems/new.html.erb
 <%= render 'form', problem: @problem %> 

app/views/problems/show.html.erb
<style>
  .gallery-image {
    width: 300px;
    height: 30%;
    object-fit: cover;
  }
</style>
<p id="notice"><%= notice %></p>
<% if (@problem.image.attached?) %>
        <%=image_tag(url_for(@problem.image),class:"gallery-image")%>
        <% else %>
          <p>no image</p>
      <% end %>
<%= link_to 'Edit', edit_problem_path(@problem), class: 'btn-outline-info' %> 
<%= link_to 'Destroy', @problem, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-outline-info' %>

<%@user.each do |user|%>
    <%= link_to 'Back',personal_page_user_path(user),  class: 'btn-outline-info' %>
<%end%>