config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :employees 
  resources :users do
    member do
      get :personal_page
    end
  end
  resources :problems do 
    member do
      get :accept
    end
  end
  ## Accept issue
  post "/acce_matt", to: "problems#accept_mat"
  post "/accept", to: "problems#accept_issue"
  get "/accept", to: "problems#accept"
  
  get "/submit", to: "problems#new"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get "/", to: "homepage#home_page"
  #home page
  get "/", to: 'homepage#home_page'

  get "/new", to: "sessions#new"
  post "/user", to: "sessions#create"
  post "/login", to: "sessions#login"
  get "/index", to: "users#index"
  get "/log_out", to: "users#log_out"
  get "/login", to: "sessions#log_in"
  get "/new_issue", to: "issues#new"
  # post "/issue", to: "issues#create"
  get "/show", to: "issues#show"
  # get "/pass", to: "employees#pass"
  post "/problem", to: "employees#update"
  get "/issue", to: "employees#issue"
  get "/new_user", to: "sessions#new_user"
  # post "/employee", to: "sessions#create_user"
  get "/user", to: "employees#user"
  get "/profile", to: "users#profile"
  post "/upprofile", to: "users#update_profile"
  post "/edit_user", to: "users#update"
  post "/pass", to: "employees#pass"
  post "/block", to: "employees#block"
  post "/active", to: "employees#active"
  get "/submit_issue", to: "problems#new"
  post "/submit_issue", to: "problems#create"
  # post "/issue_accept", to: "users#accept_issue"
  post "/feed", to: "sessions#comment"
  post "/confirm", to: "problems#confirm"
  # post "/bill_of_material", to: "users#accept_issue"
  post "/confirm_issue", to: "employees#confirm"
  get "/report", to: "employees#report"
  get "/about", to: "employees#about"
  post "/select", to: "employees#about"
  get "/confirmed_issue", to: "users#confirmed_issue"
  get "/help", to: "additions#help"
  get "/addition", to: "additions#addition"
  post "/gover", to: "additions#new_gover"
  post "/city", to: "additions#new_city"
  post "/cat", to: "additions#new_cat"
  post "/mat", to: "additions#new_mat"
  get "/accept_status", to: "users#accept_status"
  # post "/accept", to: "users#accept_problem"
  post "/join_issue", to: "users#join"
  #meassages
  get "/meassage", to: "users#meassage"
  #image
  post "/image", to: "users#upimage"
  ##personal_page
  get "/personal_page", to: "users#personal_page"
  get "/log", to: "users#log"

  ##Add Bio
  post "/bio", to: "users#add_bio"
  ## supporte money
  post "/money", to: "users#support_money"
  ## support matterails
  post '/supmat', to: "users#support_mat"

  ##spervisor
  get "/supervisor", to: "users#supervisor"
  resources :users do
    member do
      patch :accept
    end
  end
  resources :issues
  resources :employees do
    member do
      patch :block
      post :pass
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_one_attached :image
    has_secure_password
    scope :volunteer, -> { where(:user_type => "Volunteer",:status=>true)}
    # Ex:- scope :active, -> {where(:active => true)}
    validates :username, confirmation: true, uniqueness: { message: "Username already exists" }
    validates :first_name, presence: true, length: {maximum: 50}
    validates :last_name, presence: true, length: {maximum: 50}
    validates :phone, presence: true, length: {maximum: 9}
    # validates :city_id, presence: true
    
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
     layout 'application'
    #  before_action :confirm, except: [:new, :create]
    before_action :check_status
    before_action :blok_or_active, only: %i[ accept_issue join]
    before_action :check_login

    def index 
     @user = User.where(:id=>session[:user_id]) 
     @employee= User.where(:id=>session[:user_id],:user_type=>"Employee")
     @problems = Problem.issue_passed.order("id DESC").with_attached_image
     @issue=Problem.where(:id=>params[:problem_id])
    
    end
    def profile
      
      @employee= User.where(:id=>session[:user_id],:user_type=>"Employee")
      @city= City.all
      @gover= Governorate.all
      @problems=Problem.where(:user_id=> session[:user_id])
      @user = User.where(:id=>session[:user_id]) 
      @photo = Photo.find_by(user_id: session[:user_id])
    end
    def upimage 
       if User.where(:id=>session[:user_id]).save(:image=>image_params[:image])
        redirect_to "/profile"
       else
        redirect_to '/index'
       end
    end
    def update_profile
        user=User.find_by(id: session[:user_id])
        if User.where(:id=> session[:user_id]).update_all(:city_id=>update_profile_params[:city_id])
            redirect_to "/profile"
        else
            flash[:error_city]="something went wrong"
            redirect_to '/profile'
        end
    end
    def update
        @user=User.find_by(id: update_params[:id])
        if User.where(:id=>update_params[:id]).update_all(:first_name=>update_params[:first_name],:last_name=>update_params[:last_name],:username=>update_params[:username],:phone=>update_params[:phone],:bio=>params[:bio])
            redirect_to "/profile"
        else
            flash[:error_profile]="something went wrong"

            redirect_to '/profile'
        end
    end
    def destroy
        @user=User.where(:id=>params[:id]).update_all(:status=>false)
        respond_to do |format|
            format.html { redirect_to '/user', notice: "Photo was successfully destroyed." }
            format.json { head :no_content }
        end

    end
    def log_out
       
        session[:user_id]=nil
        cookies[:user_type]=nil
        
        redirect_to '/'
        
    end
    def log
        user = User.find_by(id: session[:user_id])
        if user.user_type=="Employee"
            redirect_to '/issue'
        else
            redirect_to '/index'
        end
    end
    
    def confirmed_issue
     @user = User.where(:id=>session[:user_id]) 
     @employee= User.where(:id=>session[:user_id],:user_type=>"Employee")
     @mat = Material.all
     @accepter = Accept.find_by(:user_id=>session[:user_id])
   
    end
    def accept_status
        @user = User.where(:id=>session[:user_id]) 
        @problems = Problem.accept_issue.order("id DESC").with_attached_image
        @money = MoneyType.all
        @mat = Material.all
        @accepter = Accept.find_by(:user_id=>session[:user_id])
    end
  
    def join
        join=JoinIssue.new(join_params)
        join.user_id=session[:user_id]
        join.status=true
        respond_to do |format|
            if join.save 
                format.html { redirect_to '/accept_status', notice: "you are successfully joined ." }
            else
                flash[:error_join]="something went wrong"
                redirect_to '/accept_status'
            end
        end
      
    end
    def meassage
        
    end
    def personal_page
        if user = User.where(:id=>params[:id]).present?
            @users= User.where(:id=>params[:id])
            @employee = User.where(:id=>session[:user_id],:user_type=>"Employee")
        else
            redirect_to '/index'
        end
    end
    def add_bio
       if User.where(:id=> session[:user_id]).update_all(:bio=>bio_params[:bio])
        redirect_to new_photo_path
       else
        flash[:error_bio]="something went wrong"
        redirect_to new_photo_path
       end

    end

    def support_money
        support = SupportedMoney.new(money_params)
        respond_to do |format|
            if support.save
                format.html { redirect_to '/accept_status', notice: "supported was successfully created." }
            else
                flash[:error_supp]= "something went wrong"
                redirect_to '/accept_status'
            end
        end
    end

    def support_mat
        supportmat = MaterialSupporet.new(supmat_params)
        respond_to do |format|
            if supportmat.save
                format.html { redirect_to '/accept_status', notice: "supported was successfully created." }
            else
                flash[:error_supp]= "something went wrong"
                redirect_to '/accept_status'
            end
        end
    end
    def supervisor
        @accept = Accept.find_by(:user_id=>session[:user_id])
        @problem =Problem.find_by(:id=>@accept.problem_id)
        @x = @problem.id
        @supporter_mat = MaterialSupporet.where(:problem_id=>@problem.id)
        @supporter_m = SupportedMoney.where(:problem_id=>@problem.id)
    end

    
    
    
    private
        def issue_params
            params.require(:issue).permit(:id)
        end
        
         def set_login
             @user=User.find(params[:id])
         end
         def login_params
            params.require(:user).permit(:first_name, :last_name, :phone, :username, :password, :city_id, :accountstatu)  
         end
         def update_params
            params.require(:edit_user).permit(:id,:first_name, :last_name, :username,:phone,:bio)  
         end
       
         def update_profile_params
            params.require(:upprofile).permit(:city_id)
         end
         def join_params 
            params.require(:join_issue).permit(:problem_id)
         end
         def  bio_params
            params.require(:bio).permit(:bio,:id)
         end
         def money_params
             params.require(:money).permit(:user_id, :problem_id, :amount, :money_type_id)
         end
         def supmat_params
             params.require(:supmat).permit(:user_id, :problem_id, :material_id, :quantity)
         end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/accept_status.html.erb
 <%= stylesheet_link_tag 'join'%>
<div class="h2">
    Accepted Issues
</div>

<div class="row">
    <%@problems.each do |problem|%>
        <div class="shadow-sm p-3 mb-5 bg-white rounded join-container">
            <div class="join-container2">
                <%= image_tag(problem.image, :class => "join-issue-img")  %>
                <div class="join-issue-info">
                    <div class="blog-cate53q 68=qgory">
                        <%@cat=Category.where(:id=>problem.category_id)%>
                        <%@cat.each do |cat|%>
                            <i class="far fa-newspaper"></i> <%=cat.name%> Issue
                        <% end %>
                    </div>
                    <div>
                        <div class="blog-card-caption">Location:</div>
                        <%@city=City.where(:id=>problem.city_id)%>
                        <%@city.each do |city|%>
                            <%@gover=Governorate.where(:id=>city.governorate_id)%>
                        <% end %>
                        <div>
                            <span>Governorate:</span>
                            <%@gover.each do |go|%>
                            <span><%=go.name%></span>
                            <% end %>
                        </div>
                        <div>
                            <span>City:</span>
                            <%@city.each do |city|%>
                                <span><%=city.name%></span>
                            <%end %>
                            
                        </div>
                    </div>
                    <div>
                        <div class="blog-card-caption">Description</div>
                        <div class="blog-card-description">
                            <%=problem.desciption%>
                        </div>
                    </div>
                    <div class="blog-card-caption">
                        <span>Submitted by:</span>
                        <span>
                            <%user=User.where(:id=>problem.user_id)%>
                            <%user.each do |user|%>
                                <span > <%= link_to "#{user.first_name} #{user.last_name}",personal_page_user_path(user),:class=>"link-light", :style=>"text-decoration: none;" %></span>
                            <%end%>
                        </span>
                        <span>in</span>
                        <span>
                            <%=problem.created_at.to_date%>
                        </span>
                    </div>
                    
                    <div class="blog-card-caption">
                        <span>Supervisored by:</span>
                        <span>
                            <%accept=Accept.where(:problem_id=>problem.id)%>
                            <%accept.each do |acc|%>
                                <%user=User.where(:id=>acc.user_id)%>
                            <%end%>
                            <%user.each do |user|%>
                                <span> <%= link_to "#{user.first_name} #{user.last_name}",personal_page_user_path(user),:class=>"link-light", :style=>"text-decoration: none;" %></span>
                            <%end%>
                        </span>
                        <span>in</span>
                        <span>
                            <%=problem.created_at.to_date%>
                        </span>
                    </div>
                </div>
            </div>
          
            <%# modal supporter %>
            <div class="model-container">
                <div class="model">
                    <i class="fas fa-home"></i>
                    <h3>support Box</h3>
                    <% @user.each do |user| %>
                        <p>welcome <%=user.first_name%> </p>
                        <h3>choos what you want to support</h3>
                        <div class=main>
                            <button id=ass class=on>Money</button>
                            <button id=on class=off>Matt</button>
                        </div>
                        <div class=money>
                            <form action=/money method=POST>
                                <input type='hidden' name='authenticity_token' value="<%= form_authenticity_token%>">
                                <input type=hidden name=money[user_id] value=<%= user.id%>>
                                <input type=hidden name= money[problem_id] value=<%= problem.id%>>
                                <input type=number name=money[amount] class="sel ">
                                <select class="sel" name=money[money_type_id]>
                                <option><option>
                                <% @money.each do |mo| %>
                                    <option value= <%= mo.id %>><%= mo.coins %><option>
                                <% end %>
                                </select>
                                    <button class="btn-money">Support</button>
                            </form>
                        </div>
                        <div class="matt">
                            <form action=/supmat method=POST>
                                <input type='hidden' name='authenticity_token' value="<%= form_authenticity_token%>">
                                <input type=hidden name=supmat[user_id] value=<%= user.id%>>
                                <input type=hidden name= supmat[problem_id] value=<%= problem.id%>>
                                <select class="form-control w-50" name=supmat[material_id]>
                                <option><option>
                                <% @mat.each do |mat| %>
                                <option value=<%=mat.id%>><%= mat.name %></option>
                                <% end %>
                                </select>
                                <input type=number class="form-control w-50" name=supmat[quantity]>
                                <button >Support</button>
                            </form>
                            </div>
                    <% end %>

                        <i class="fas fa-times close"></i>
                </div>
            </div>

            <div class="support-join-btns">
                <div>
                    <% accept = Accept.find_by(:problem_id => problem.id )%>
                    <% if accept.totale_cost ==3000 %>
                        <input  style="width:100px"type=submit class='btn btn-outline-info' value=Supported disabled>
                    <% else %>
                        <button id="support" class='btn btn-outline-info'>Support</button>
                    <% end %>
                </div>

                <div>
                    <% if @accepter.present? %>
                    <input  style="width:100px"type=submit class='btn btn-outline-info w-100' value='your already Supervisor' disabled>
                    <% else %>
                        <%join=JoinIssue.where(:user_id=>session[:user_id],:status=>true)%>
                        <%join_user=JoinIssue.where(:problem_id=>problem.id ,:user_id=>session[:user_id], :status=>true)%>
                        <%if join_user.present?%>
                            <input style="width:100px" type=submit class='btn btn-outline-info' value=Joined disabled>
                        <%elsif join.present?%>
                                <input style="width:auto" type=submit class='btn btn-outline-info' value="you're joined in another issue" disabled>
                        <%else%>
                            <%= form_tag({:controller=>'users',:action=>'join'},:remote=> true, method: :post) do%>

                                <%# <input type='hidden' name='authenticity_token' value="<%= form_authenticity_token%>
                                <input type=hidden name=join_issue[problem_id] value=<%=problem.id%>>
                                <%@accept=Accept.where(:problem_id=>problem.id)%>
                                <%@accept.each do |acc|%>
                                    <%if acc.required_volunteer == JoinIssue.where(:problem_id=>problem.id).count%>
                                        <input  style="width:100px"type=submit class='btn btn-outline-info' value=Join disabled>
                                    <%else%>
                                        <input style="width:100px"  type=submit class='btn btn-outline-info' value= Join>
                                    <%end%>
                                <%end%>
                            <% end %>
                        <%end%>
                    <% end %>
                </div>
            </div>
        </div>
    <%end%>
</div>
<a class="border rounded d-inline scroll-to-top" href="" style="margin-right: 60px;">
    <i class="fas fa-angle-up"></i>
</a>
<a class="border rounded d-inline scroll-to-top" href="/submit_issue">
    <button class="btn btn-primary add-issue fa fa-plus" type="button" data-toggle="modal" data-target="#submit_issue"></button>
<a> 
<script>
    $(function(){
        $('#support').click(function(){
            $('.model-container').delay(2000).css('transform',' scale(1)')
        });
        
        $('body').on('click','.close',function(){
            $('.model-container').css('transform',' scale(0)')
        });
        
        $('.off').click(function(){
            $('.money').hide()
            $('.matt').show()
            $('.off').delay(2000).css('background','rgb(50, 150, 250)')
            $('.on').delay(2000).css('background','#fff')
        });
        $('.on').click(function(){
            $('.money').show()
            $('.matt').hide()
            $('.on').delay(5000).css('background','rgb(50, 150, 250)')
            $('.off').delay(5000).css('background','#fff')
        });
        // $(".show-details").click(function(){
        //     $(this).parents(".join-issue-info").css('display','flex')
        // })
    });
</script>

app/views/users/confirmed_issue.html.erb
<%= stylesheet_link_tag 'index' %>

<div id="wrapper">
  <div class="container-fluid">
    <div class="d-sm-flex justify-content-between align-items-center mb-4">
      <h3 class="text-dark mb-0">Confirmed Issues</h3>
    </div>
    <div class="container">
      <% @user.each do |user| %>
        <%@problems=Problem.where(:status=>"Confirmed").with_attached_image%>
          <%end%>
            <% @problems.each do |problem| %>
              <div class="instagram-card shadow-sm p-3 mb-5 bg-white rounded">
              <div class="submitted-issue-img-likes">
                <div class="instagram-card-header">
                  <div>
                    <% @submiter = User.where(:id=> problem.user_id)%>
                    <% @submiter.each do |user| %>
                      <%if @photos=Photo.where(:user_id=>user.id).present?%>
                        <%@photos= Photo.where(:user_id=>user.id)%>
                          <% @photos.each do |photo| %>
                            <% if (photo.image.attached?) %>
                              <%=image_tag(url_for(photo.image),class:"instagram-card-user-image")%>
                            <% else %>
                              <%=image_tag('avatar.png', class:"instagram-card-user-image")%>
                            <% end %>
                          <% end %>
                        <% else %>
                          <%=image_tag('avatar.png', class:"instagram-card-user-image")%>
                            <% end %>
                              <span class="instagram-card-user-name">
                                <%=user.first_name%>
                                  <%=user.last_name%>
                              </span>
                      <%end%>
                  </div>
                  <button id="myBtn" class="three-dots fa fa-ellipsis-h"></button>
                </div>

                <div class="intagram-card-image">
                  <% if (problem.image.attached?) %>
                    <%=image_tag(url_for(problem.image))%>
                      <% else %>
                        <p>no image</p>
                        <% end %>
                </div>
                <div class="category-date">
                  <% @category=Category.where(:id=>problem.category_id)%>
                  <% @category.each do |category| %>
                    <div class="blog-category blog-text-success issue_info_parts">
                      <%= category.name%>
                    </div>
                    <% end %>
                  <div class="issue_date blog-text-success">
                    <span>Date:</span>
                      <%=problem.created_at.to_date%>
                  </div>
                </div>
                <div>
                  <div class="like-unlike">
                    <div class="like">
                      <button disabled><i class="far fa-thumbs-up un-like"></i></button>
                      <span>
                        <%=Confirm.where(:problem_id=>problem.id,:confirmed=>true).count%>
                      </span>
                    </div>
                    <div>
                      <button disabled><i class="far fa-thumbs-down un-like"></i></button>
                      <span>
                        <%=Confirm.where(:problem_id=>problem.id,:confirmed=>false).count%>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
                <div class="blog-table">
                  <div class="issue_info_parts">
                      <h4 class="blog-card-caption">Location:</h4>
                      <div class="blog-card-description">
                        <span>Governorate:</span>
                        <%@city=City.where(:id=>problem.city_id)%>
                          <% @city.each do |city| %>
                            <%@gove=Governorate.where(:id=>city.governorate_id)%>
                              <% @gove.each do |gove| %>
                                  <span>
                                    <%=gove.name%>
                                  </span>
                              <% end %>
                            <% end %>
                  </div>
                          <div class="blog-card-description">
                            <span>City:</span>
                            <% @city.each do |city| %>
                              <span>
                                <%=city.name%>
                              </span>
                              <%end%>
                          </div>
                        </div>

                        <div class="issue_info_parts">
                          <h4 class="blog-card-caption">Description</h4>
                          <p class="blog-card-description">
                            <%=problem.desciption%>
                          </p>
                        </div>
                        <div class="issue_info_parts">
                          <h4 class="blog-card-caption">Status</h4>
                          <p class="blog-card-description">
                            <%=problem.status%>
                          </p>
                        </div>
                        <div class="issue_info_parts">
                          <h4 class="blog-card-caption">Submitted by:</h4>
                          <div class="blog-card-description">
                            <span>user:</span>
                            <%@submiter=User.where(:id=> problem.user_id)%>
                              <% @submiter.each do |user| %>
                                <span>
                                  <%= link_to "#{user.first_name} #{user.last_name}",personal_page_user_path(user),:class=>"link-dark" %>
                                </span>
                                <% end %>
                          </div>
                        </div>
                        <div class="container">
                          <button id="open" class=open>View all <span id=number-cmt>
                              <%=Coment.where(:problem_id=>problem.id).count%>
                            </span> comments</button>
                        </div>
                          <% if @accepter.present?%>
                            <input  style="width:100px"type=submit class='btn btn-outline-info w-100' value='your already Supervisor' disabled>

                          <% else %>
                            <%# <button class="btn btn-outline-info w-100" id="btn-accept">Accept</button> %>
                            <%= link_to "Accept", accept_problem_path(problem), class:"btn btn-outline-info w-100"%>
                          <% end %>
                </div>
                <div class="model-container" tabindex="-1">
                  <div class="model">
                    <div class="instagram-card-header">
                      <div>
                        <%@user.each do |user|%>
                          <%if @photos=Photo.where(:user_id=>user.id).present?%>
                            <%@photos= Photo.where(:user_id=>user.id)%>
                              <% @photos.each do |photo| %>
                                <% if (photo.image.attached?) %>
                                  <%=image_tag(url_for(photo.image),class:'instagram-card-user-image')%>
                                <% else %>
                                  <%=image_tag('avatar.png',class:'instagram-card-user-image')%>
                                <% end %>
                              <% end %>
                            <% else %>
                              <%=image_tag('avatar.png',class:'instagram-card-user-image')%>
                            <% end %>
                              <span class="instagram-card-user-name">
                                <%=user.first_name%>
                                <%=user.last_name%>
                              </span>
                          <%end%>
                      </div>
                    </div>
                    <%@comments=Coment.where(:problem_id=>problem.id)%>
                      <%@comments.each do |com|%>
                        <div class="users-comments">
                          <div class="cmt">
                            <%user=User.where(:id=>com.user_id)%>
                              <%user.each do |user|%>
                                <%if @photos=Photo.where(:user_id=>user.id).present?%>
                                  <%@photos=Photo.where(:user_id=>user.id)%>
                                    <% @photos.each do |photo| %>
                                      <% if (photo.image.attached?) %>
                                        <%=image_tag(url_for(photo.image),class:'instagram-card-user-image')%>
                                      <% else %>
                                        <%=image_tag('avatar.png',class:'instagram-card-user-image')%>
                                      <% end %>
                                    <% end %>
                                  <% else %>
                                    <%=image_tag('avatar.png',class:'instagram-card-user-image')%>
                                  <% end %>
                                    <div class="instagram-card-user-name">
                                      <%=user.first_name%>
                                        <%=user.last_name%>
                                    </div>
                              <%end%>
                              <div class="cmt-txt">
                                <%=com.comment%>
                              </div>
                          </div>
                        </div>
                      <%end%>
                          <div class="instagram-card-footer"></div>
                          <i class="fas fa-times close"></i>
                  </div>

                </div>
               
              </div>
              <%end%>
    </div>
  </div>

<a class="border rounded d-inline scroll-to-top" href="" style="margin-right: 60px;">
  <i class="fas fa-angle-up"></i>
</a>
<a class="border rounded d-inline scroll-to-top" href="/submit_issue">
  <button class="btn btn-primary add-issue fa fa-plus" type="button" data-toggle="modal"
    data-target="#submit_issue">
  </button>
<a>
<script>
  $(function () {
    $('.open').click(function () {
      $(this).click(function () {
        $('.model-container').delay(2000).css('transform', ' scale(1)')
      });
    });
    $('body').on('click', '.close', function () {
      $('.model-container').css('transform', ' scale(0)')
    });
  });
</script>