config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :employees 
  resources :users do
    member do
      get :personal_page
    end
  end
  resources :problems do 
    member do
      get :accept
    end
  end
  ## Accept issue
  post "/acce_matt", to: "problems#accept_mat"
  post "/accept", to: "problems#accept_issue"
  get "/accept", to: "problems#accept"
  
  get "/submit", to: "problems#new"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get "/", to: "homepage#home_page"
  #home page
  get "/", to: 'homepage#home_page'

  get "/new", to: "sessions#new"
  post "/user", to: "sessions#create"
  post "/login", to: "sessions#login"
  get "/index", to: "users#index"
  get "/log_out", to: "users#log_out"
  get "/login", to: "sessions#log_in"
  get "/new_issue", to: "issues#new"
  # post "/issue", to: "issues#create"
  get "/show", to: "issues#show"
  # get "/pass", to: "employees#pass"
  post "/problem", to: "employees#update"
  get "/issue", to: "employees#issue"
  get "/new_user", to: "sessions#new_user"
  # post "/employee", to: "sessions#create_user"
  get "/user", to: "employees#user"
  get "/profile", to: "users#profile"
  post "/upprofile", to: "users#update_profile"
  post "/edit_user", to: "users#update"
  post "/pass", to: "employees#pass"
  post "/block", to: "employees#block"
  post "/active", to: "employees#active"
  get "/submit_issue", to: "problems#new"
  post "/submit_issue", to: "problems#create"
  # post "/issue_accept", to: "users#accept_issue"
  post "/feed", to: "sessions#comment"
  post "/confirm", to: "problems#confirm"
  # post "/bill_of_material", to: "users#accept_issue"
  post "/confirm_issue", to: "employees#confirm"
  get "/report", to: "employees#report"
  get "/about", to: "employees#about"
  post "/select", to: "employees#about"
  get "/confirmed_issue", to: "users#confirmed_issue"
  get "/help", to: "additions#help"
  get "/addition", to: "additions#addition"
  post "/gover", to: "additions#new_gover"
  post "/city", to: "additions#new_city"
  post "/cat", to: "additions#new_cat"
  post "/mat", to: "additions#new_mat"
  get "/accept_status", to: "users#accept_status"
  # post "/accept", to: "users#accept_problem"
  post "/join_issue", to: "users#join"
  #meassages
  get "/meassage", to: "users#meassage"
  #image
  post "/image", to: "users#upimage"
  ##personal_page
  get "/personal_page", to: "users#personal_page"
  get "/log", to: "users#log"

  ##Add Bio
  post "/bio", to: "users#add_bio"
  ## supporte money
  post "/money", to: "users#support_money"
  ## support matterails
  post '/supmat', to: "users#support_mat"

  ##spervisor
  get "/supervisor", to: "users#supervisor"
  resources :users do
    member do
      patch :accept
    end
  end
  resources :issues
  resources :employees do
    member do
      patch :block
      post :pass
    end
  end
end

app/models/accept.rb
class Accept < ApplicationRecord
end

app/models/accept_mat.rb
class AcceptMat < ApplicationRecord
end

app/models/accept_money.rb
class AcceptMoney < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, confirmation: true, uniqueness: { message: "this category already exists" }
    
    
end

app/models/city.rb
class City < ApplicationRecord
    belongs_to :governorate
    validates :name, presence: true
    validates :governorate_id, presence: true
    
    
    
    
end

app/models/coment.rb
class Coment < ApplicationRecord
    validates :comment, presence: true
    
end

app/models/confirm.rb
class Confirm < ApplicationRecord
end

app/models/governorate.rb
class Governorate < ApplicationRecord
    has_many :cities
    validates :name, presence: true
    
    
end

app/models/issue.rb
class Issue < ApplicationRecord
    has_one_attached :image
    belongs_to :city
    
end

app/models/join_issue.rb
class JoinIssue < ApplicationRecord
end

app/models/material.rb
class Material < ApplicationRecord
    validates :name, presence: true
    validates :category_id, presence: true
    
    
    
    
end

app/models/meassage.rb
class Meassage < ApplicationRecord
end

app/models/money_type.rb
class MoneyType < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
    has_one_attached :image

end

app/models/problem.rb
class Problem < ApplicationRecord
    has_one_attached :image

    scope :issue_submitted, -> { where(:status => "Submitted")}
    scope :issue_passed, -> { where(:status => "Passed")}
    scope :issue_confirmed, -> { where(:status => "confirmed")}
    scope :accept_issue, -> { where(:status => "Accepted")}
    # Ex:- scope :active, -> {where(:active => true)}
    # scope :desc,  order("problems.id DESC")
    # Ex:- scope :active, -> {where(:active => true)}
    validates :image, presence: true
    
    def self.search(search)
        if search
            # where([["status LIKE ?","%#{search}%"]])
            where(["status LIKE ?","%#{search}%"])
        else
            issue_passed
        end
    end

    # Ex:- scope :active, -> {where(:active => true)}
end

app/models/supported_money.rb
class SupportedMoney < ApplicationRecord
end

app/models/unit_of_measure.rb
class UnitOfMeasure < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_one_attached :image
    has_secure_password
    scope :volunteer, -> { where(:user_type => "Volunteer",:status=>true)}
    # Ex:- scope :active, -> {where(:active => true)}
    validates :username, confirmation: true, uniqueness: { message: "Username already exists" }
    validates :first_name, presence: true, length: {maximum: 50}
    validates :last_name, presence: true, length: {maximum: 50}
    validates :phone, presence: true, length: {maximum: 9}
    # validates :city_id, presence: true
    
    

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  layout :false
  before_action :set_photo, only: %i[ show edit update destroy ]
  before_action :check_login
  before_action :check_status

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1 or /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)
    user=User.find_by(:id=>session[:user_id]) 
    respond_to do |format|
      if @photo.save
        if user.user_type=="Employee"
          format.html { redirect_to new_photo_path, notice: "Photo was successfully created." }
          format.json { redirect_to '/issue', status: :created, location: @photo }
        elsif user.user_type=="Volunteer"
          format.html { redirect_to new_photo_path, notice: "Photo was successfully created." }
          format.json { redirect_to '/index', status: :created, location: @photo }
        end
        else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to '/profile' , notice: "Photo was successfully updated." }
        format.json { redirect_to '/profile' }
      else
        format.html { redirect_to '/profile' , notice: "Photo was successfully updated." }
        format.json { redirect_to '/profile' }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      
      params.require(:photo).permit(:image, :user_id)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/meassges_helper.rb
module MeassgesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.file_field :image %>
    <%= form.hidden_field(:user_id, value:session[:user_id]) %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<style>
    .avatar {
    vertical-align: middle;
    width: 225px;
    height: 225px;
    border-radius: 50%;
  }

</style>
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
     <% if (photo.image.attached?) %>
      			                    		  <%=image_tag(url_for(photo.image),class:'avatar')%>
      			                    		<% else %>
                                       		<%=image_tag('avatar.png')%> 
      			                    		<% end %>
      <tr>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
 <%= stylesheet_link_tag 'profile_personaly'%>


<body>
    <header class= ' chatbar'>
            <div class=header>
                <i class="fa fa-arrow-left"></i>

                <span>profile personaly</span>
                 <a class=skip href="/log" >
                <span>Skip </span>
                <i class="fas fa-fast-forward"></i>
            <a>
            <div>
            
    </header>
    <div class=' row picture-profile'>
        <%if  @photos= Photo.where(:user_id=>session[:user_id]).present?%>
			<%@photos= Photo.where(:user_id=>session[:user_id])%>

            <% @photos.each do |photo| %>
      			<% if (photo.image.attached?) %>
      			    <%=image_tag(url_for(photo.image),class:"profile-pic")%>
                      
      			<% else %>
                    <%=image_tag('avatar.png',class:"profile-pic")%> 
      			<% end %>
			<% end %>
        <%else%>
            <%=image_tag('avatar.png',class:"profile-pic")%> 
            <%= form_for( @photo , remote: true) do |form| %>
                <%= form.hidden_field(:user_id, value:session[:user_id]) %>
                <%=form.label :image do%>
                    <span style="display:none;">
                    <%= form.file_field :image,class: 'form-control' %>
                    </span>
                        <div class='btn-camera btn btn-primary btn-sm' >
                            <i class="fa-solid fa-camera"></i> 
                        </div>
                <%end%>
                <input type=submit value='Add Photo'class='bnt-save btn btn-primary btn-sm'>
            <% end %>
        <%end%>
    </div>
    <div class=info>
        <a class="span nav-link" >
            <i class="fas fa-user-circle"></i>
            <span>Full Name:</span>
        </a>
        <%user= User.where(:id=>session[:user_id])%>
        <%user.each do |user|%>
            <label class="form-control"> <%=user.first_name%>&nbsp;&nbsp;<%=user.last_name%></label>
            </div>
            <form action=/bio method=POST>
                <label>Bio</label>
                <input type='hidden' name='authenticity_token' value="<%= form_authenticity_token%>">
                <input type=hidden name=bio[id] value=<%=user.id%>>
                <input type=text name=bio[bio] class="form-control"placeholder="Add Your Bio..." ,rows="5" ,cols="30" value=<%=user.bio%>>
                <input type=submit class="btn btn-primary btn-sm" value='Add Bio'>
            </form>
            <div>
                <a class="nav-link" >
                    <i class="fa fa-phone"></i>
                    <span>Phone Number:</span>
                </a>
                <label class="form-control"> <%=user.phone%></label>
            </div>
        <%end%>

</body>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>